config/routes.rb
# THE MODUS OPERANDI
# ******************************************************************************************
# 1. A req is made to a route e.g 'http://localhost:3000/about'
# The router then looks for the pages folder('pages#about') and locate the 'PagesController'
# Inside the controller it looks for the 'about' method and calls it.
# The 'about' mtd then looks for the corresponding views(about.html.erb) inside the 'views folder'
# The 'about.html.erb' is then injection into 'application.html.erb' via '<%= yield %>' in the body
# **************************************************************************************************

Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users, controllers: {registrations: 'users/registrations'}
  resources :users do
    resource :profile
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #This means a user points its request to d "pages" controller and calls the "home" mtd
  #The controller then picks the corresponding 'home page in the views' and sends to d user
  
  get 'about', to: 'pages#about' #A 'get' req points to '/about' and calls about mtd in pages controller
  resources :contacts, only: [:create] #short way of writing route
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Any object you want your applicatn to work with is stored here
  # e.g A User object whenever a user signs up will contain an array of objects
  # The model file is the blue print for our objects,used in creating objects

  # Contact Form validations
  validates :name, presence: true, length: { maximum: 120 }
  validates :email, presence: true, length: { maximum: 25 }
  validates :comments, presence: true, length: { maximum: 1200 }
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
# The Profile model programmatically has access to all the fields in the profile schema
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' },
                             default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: %r{\Aimage/.*\z}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :plan
  has_one :profile
  attr_accessor :stripe_card_token
  def save_with_subscription
    return unless valid?

    customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
    self.stripe_customer_token = customer.id
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Whitelist the form fields
  protected

  def configure_permitted_parameters
    # rubocop:disable  Layout/LineLength
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    # rubocop:enable  Layout/LineLength
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # Anytime this code runs, it creates a new blank 'contact obj' in the machine memory
  def new
    @contact = Contact.new # An instance of the Contact class in the model
  end

  # POST request to /contacts
  def create
    # Mass assignment of form fields into @contact object
    @contact = Contact.new(contact_params)
    # Save the Contact object to db
    if @contact.save
      # Store form fields frm the Parameters, into variables
      name = params[:contact][:name] # Goto the contact form and grab the 'name', the user out in.
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Put the variables into Contact Mailer email mts and send email
      ContactMailer.contact_email(name, email, body).deliver
      # Store message in flash hash and redirect_to 'new' action
      flash[:success] = 'Contact information saved!'
      # rubocop:disable Style/IdenticalConditionalBranches
      redirect_to new_contact_path

    else
      flash[:danger] = @contact.errors.full_messages.join(', ')
      redirect_to new_contact_path
      # rubocop:enable Style/IdenticalConditionalBranches
    end
  end
  #   Whitelist info collected fromm the forms -- meaning ensure info is securely saved to Db
  # To collect data from form, we need to use strong parameters and whitelist the form fields

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end

  def about; end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    # We can initantialize instance variables in our controller and make it available in the views
    @profile = Profile.new
  end

  # POST   /users/:user_id/profile
  def create
    # Ensure we have the user filling out the form
    @user = User.find(params[:user_id])
    # create profile associated with this specific user
    # we use '@user.build_profile' bcos a user 'has_one' profile
    # we will use '@user.profiles.build' for a user 'has_many' profiles
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = 'Profile Successfully created'
      redirect_to user_path(params[:user_id]) # we need to pass in an 'id' bcos of the URI '/users/:id'
    else
      render action: :new

    end
    # Only this whitelisted fields can go to out db
  end

  private

  def profile_params
    params.require(:profile)
      .permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #  GET    /users/:id
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
    def job_title_icon
        if @user.profile.job_title == "Developer"
            "<i class='fa fa-code'></i>".html_safe
        elsif @user.profile.job_title == "Entrepreneur"
            "<i class='fa fa-lightbulb-o'></i>".html_safe   
           
        elsif @user.profile.job_title == "Investor"
            "<i class='fa fa-dollar'></i>".html_safe   
        end    
    end    
    
end

app/views/contacts/new.html.erb
<div class="container mt-5">
  <h3 class="text-center h1">Contact Us</h3>
  <div class="row">
    <div class="col-md-4 offset-4">
      <div class="card">
        <div class="card-header text-center h2 text-muted">
          EntreLab
        </div>
        <div class="card-body">
          <%= form_for @contact do |f| %>
            <div class="form-group">
              <%= f.label :name, "Your name" %>
              <%= f.text_field :name,class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :email, "Your email" %>
              <%= f.text_field :email, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :comments, "Your comments" %>
              <%= f.text_area :comments, class: 'form-control' %>
            </div>
            <%= f.submit "Submit", class: 'form-control btn btn-info btn-block' %>
            <!-- form_for @object, html: { multipart: true }, do |f| -->
            <!-- form_for @object, html: { class: "classname" }, do |f| -->
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntreLab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Font Awesome %>
    <%# <script src="https://kit.fontawesome.com/18a281af1f.js" crossorigin="anonymous"></script> %>
    <%# Google Fonts %>
    <link href="//fonts.googleapis.com/css2?family=Open+Sans:wght@400;700;800&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/', type: 'text/javascript' %>
    <%# <script src="https://js.stripe.com/v3/"></script> %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
    <%# <script>
      var stripe = Stripe(STRIPE_PUBLIC_KEY);
    </script> %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%# <a class="navbar-brand text-white" href="/"><i class="fa fa-language" aria-hidden="true"></i> EntreLab</a> %>
      <%= link_to root_path, class: "navbar-brand text-white"  do %>
        <i class="fa fa-language" aria-hidden="true"></i> EntreLab
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%# <a class="nav-link" href="/about">About</a> %>
            <%# using URI pattern '/about' %>
            <%# <%= link_to "About", "/about", class: "nav-link" %>
            <%# Using prefix for dynamic routing %>
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact Us", new_contact_path, class: "nav-link" %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <%# <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> %>
          <%# <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> %>
          <% if user_signed_in? %>
            <%= link_to "Log Out",  destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-success my-2 my-sm-0 mr-3" %>
          <% else %>
            <%= link_to "Log In",  new_user_session_path, class: "nav-link btn btn-outline-success my-2 my-sm-0 mr-3" %>
            <%# <%= link_to "Sign Up",   new_user_registration_path, class: "nav-link btn btn-outline-info my-2 my-sm-0" %>
          <% end %>
        </form>
      </div>
    </nav>
    <div class="container">
      <% flash.each do | type, msg | %>
        <%= content_tag :div, msg, class: "mt-3 alert alert-#{type}" %>
      <%end%>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <h1 class="display-3">Welcome to about - EntreLab</h1>
    <p class="lead">We are EntreLab. Our company is commited to building a community of developers and entrepreneurs to help translate skills into earnings..., We are constantly evevolving to meet your needs.</p>
    <hr class="my-2">
    <p>More info</p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="Jumbo action link" role="button">Check this out</a>
    </p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="landing-banner text-center container-fluid py-5 text-white mb-4">
  <h1>Welcome to EntreLab</h1>
  <h3>Meet entrepreneurs to convert your skills into <strong class="text-dark">$</strong><span class="text-info">earnings...<i class="fa fa-money mr-2" aria-hidden="true"></i></span></h3>
</div>
<div class="container mb-4">
  <div class="row">
    <div class="col-md-6">
      <div class="card text-center">
        <div class="card-body">
          <h4 class="card-title text-muted">Basic Membership Plan</h4>
          <p class="card-text">Sign up for free and get basic access to the community. But you can get more for Pro Membership!</p>
        </div>
        <div class="card-body">
          <%= link_to "Sign up with Basic Plan", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card text-center">
        <div class="card-body">
          <h4 class="card-title text-muted">Pro Membership Plan</h4>
          <p class="card-text">Sign up for the pro account for $10/month and get access to the community and contact information!</p>
        </div>
        <div class="card-body">
          <%= link_to "Sign up with Pro Plan", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
    </div>
  </div>
  <div><%= puts current_user.email if user_signed_in? %></div>
  <%# User devise current_user method to get the currently signedin user %>
  <%= link_to "Create your profile",  new_user_profile_path(user_id: current_user.id) if user_signed_in? %>
</div>

app/views/profiles/_profile_form.html.erb
<div class="card">
  <div class="card-header text-center h2 text-muted">
    EntreLab
  </div>
  <%# Form field must tally with what we have in the profile schema %>
  <div class="card-body">
    <%= form_for @profile, url: user_profile_path, html: { multipart: true } do |f| %>
      <%# <%= hidden_field_tag 'plan', params[:plan] %>
      <div class="form-group">
        <%= f.label :first_name %><br />
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :job_title %>
        <%= f.select :job_title,['Developer','Entrepreneur', 'Investor'],{}, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :contact_email %>
        <%= f.text_field :contact_email, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="field form-group mb-4">
        <div class="actions">
          <%= f.submit "Save profile", class: 'form-control btn btn-info btn-block' %>
        </div>
      <% end %>
    </div>
  </div>

app/views/profiles/new.html.erb
<%# <h1>profile</h1> %>
<%# <%= @me %>
<%# <%= debug(params) if Rails.env.development? %>
<div class="container my-5">
  <h2 class="text-center h1 mb-3">Create Your Profile</h2>
  <p class="card-text text-center text-muted">Be a part of EntreLab community! <strong>Fill out your profile</strong></p>
  <%# <h2 class="text-center h1 mb-3">Sign up</h2> %>
  <div class="row">
    <div class="col-md-6 offset-3">
      <%= render 'profile_form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%# <%= @user.inspect %>
<%# <%= @user.profile.inspect %>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @user.profile.avatar.url(:thumb), class: 'avatar-img' %>
    </div>
    <div class="col-md-6">
      <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
      <h3><span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %></h3>
      <div class="card profile-block profile-desc">
        <div class="card-body">
          <h4 class="card-title">Description</h4>
          <p class="card-text"> <%= @user.profile.description %></p>
        </div>
      </div>
      <% if current_user.plan_id == 2 %>
        <div class="card profile-block profile-contact-info">
          <div class="card-body">
            <h4 class="card-title">Contact Information</h4>
            <p class="card-text"><%= @user.profile.phone_number %></p>
            <p class="card-text"><%= @user.profile.contact_email %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%# <%= image_tag @user.profile.avatar.url %>
<%# <%= image_tag @user.profile.avatar.url(:medium) %>
<%# <%= image_tag @user.profile.avatar.url(:thumb) %>